doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
    driver: 'pdo_pgsql'
    server_version: '13.6'
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        dir: '%kernel.project_dir%/src'
        prefix: 'App'
        alias: App
    dql:
      numeric_functions:
        earth_box: App\Common\Doctrine\Postgres\EarthBox
        ll_to_earth: App\Common\Doctrine\Postgres\LLToEarth
        earth_distance_operator: App\Common\Doctrine\Postgres\EarthDistanceOperator
        earth_distance: App\Common\Doctrine\Postgres\EarthDistance

when@prod:
  doctrine:
    orm:
      auto_generate_proxy_classes: false
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool

  framework:
    cache:
      pools:
        doctrine.system_cache_pool:
          adapter: cache.system
