# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  param_fetcher_listener: force
  allowed_methods_listener: true
  routing_loader: false
  view:
    view_response_listener: true
  exception:
    enabled: true
    map_exception_codes: true
    exception_listener: false
    serialize_exceptions: false
  #  exception:
  #    codes:
  #      App\Exception\MyException: 403
  #    messages:
  #      App\Exception\MyException: Forbidden area.
  body_converter:
    enabled: true
    validate: true
    validation_errors_argument: validationErrors
  body_listener:
    enabled: true
    default_format: json
    throw_exception_on_unsupported_content_type: true
  format_listener:
    rules:
      - { path: ^/api/v1, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
      - { fallback_format: html }
