security:
  enable_authenticator_manager: false
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
  providers:
    users_in_memory: { memory: null }
  firewalls:
    empty:
      security: false

  access_control:
